apiVersion: v1
kind: Pod
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  containers:
    - name: backend-app
      image: arbazmalik/cafe-backend:4
      ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30009

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    app: frontend-app
    name: frontend
spec:
  containers:
    - name: frontend-app
      image: arbazmalik/cafe-frontend:latest
      ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  type: NodePort
  selector:
    app: frontend-app
    name: frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30008

---
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  containers:
    - name: mysqldb
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "cafe"
      ports:
        - containerPort: 3306

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30005
  type: NodePort
